apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-4mins
  namespace: todoapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: ikulyk404/busyboxplus:curl
            command:
              - /bin/sh
              - -c
            args:
              - |
               curl -s http://todoapp.todoapp.svc.cluster.local:80/api/health
          