apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: curl-with-busybox
  namespace: mateapp
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: ikulyk404/busyboxplus:curl
        command:
            - /bin/sh
            - -c
        args:
          - |
           while true; do
            curl -s http://todoapp.todoapp.svc.cluster.local:80 
            sleep 5
           done
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
